### ISSUE TITLE
Problems with Windows OS

### ISSUE THREAD

**Issue by DataIntellSystLab** [indeedeng/mph-table#12]
It seems that there are no mmap Windows OS-specific native files (it may be one of the dependencies). Given the issues with memory mapped files on windows, is this a hard no-go?

**Comment by ashinn** [comment]
We could probably use [MappedByteBuffer](https://docs.oracle.com/javase/8/docs/api/java/nio/MappedByteBuffer.html).

**Comment by coffeesippa** [comment]
@DataIntellSystLab thanks for reporting this issue. We have determined that we will no longer move forward with this project and will set it to archive status on 7/11. If you would like to maintain and add the windows support, please create a fork.
