### ISSUE TITLE
Try other minimal perfect hash functions?

### ISSUE THREAD

**Issue by jermp** [indeedeng/mph-table#8]
Hi there,
I found your blog post https://engineering.indeedblog.com/blog/2018/02/indeed-mph/,
where you describe a key-value store based on MPHF.
And thanks for open-source it!

I wonder whether, apart from GOV, you are interested in other MPHF as to
improve the efficiency of your store.
For example, you may want to consider this new method:
PTHash, https://github.com/jermp/pthash (although it is written in C++, not Java).
The method is fully described in the following two papers:
- https://arxiv.org/abs/2104.10402
- https://arxiv.org/abs/2106.02350

Cheers,
-Giulio

**Comment by ashinn** [comment]
Thanks Giulio!  I was familiar with some other techniques but hadn't seen PTHash.  It's unlikely we'd use a C++ library, but the papers look interesting, I'll enjoy reading them :)

**Comment by jermp** [comment]
Hi Alex and thank you for your interest.
Can you thus confirm that a Java implementation of PTHash
could be of interest to you?
